sonar.projectKey=Oslandia_french_locator_filter
sonar.organization=oslandia

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName="French Locator Filter"
#sonar.projectVersion=1.0
sonar.python.version=3.8, 3.9, 3.10

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=french_locator_filter

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Python configuration
sonar.language=python3
sonar.python.file.suffixes=py
sonar.python.coverage.reportPaths=coverage-reports/*coverage-*.xml
sonar.python.xunit.reportPath=junit/test-results-*.xml
sonar.coverage.exclusions=**__init__**,tests/**,*.py
sonar.exclusions=*.xml,doc/**

sonar.host.url=https://sonarcloud.io
