# This file is auto-generated by the script generate_translation_profile.py
# Do not edit this file manually

FORMS =	../../gui/dlg_settings.ui \
	../../gui/wdg_reverse_geocoding.ui \
	../../toolbelt/wdg_point_selection.ui

SOURCES =	../../core/geocoder/addok_ban_fr_geocoder.py \
	../../core/geocoder/photon_geocoder.py \
	../../core/geocoder/rest_api_geocoder.py \
	../../core/locator_filter/addok_ban_fr_locator_filter.py \
	../../core/locator_filter/photon_locator_filter.py \
	../../core/locator_filter/rest_api_locator_filter.py \
	../../gui/dlg_settings.py \
	../../gui/mdl_geocoder_result.py \
	../../gui/wdg_reverse_geocoding.py \
	../../plugin_main.py \
	../../processing/gpf_geocoder_batch_processing.py \
	../../processing/gpf_inverse_geocoder_batch_processing.py \
	../../processing/inverse_geocoder_batch_processing.py \
	../../processing/photon_geocoder_batch_processing.py \
	../../processing/photon_inverse_geocoder_batch_processing.py \
	../../processing/provider.py \
	../../processing/utils.py \
	../../toolbelt/log_handler.py \
	../../toolbelt/network_manager.py \
	../../toolbelt/preferences.py \
	../../toolbelt/wdg_point_selection.py

TRANSLATIONS =	french_locator_filter_en.ts \
	french_locator_filter_fr.ts
