#!python3

"""
Configuration for project documentation using Sphinx.
"""

# standard
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Union

# 3rd party
import keepachangelog

# move into project package
sys.path.insert(0, f"{Path(__file__).parent.parent.resolve()}")


# Package
from french_locator_filter import __about__

logger: logging.Logger = logging.getLogger(__name__)

# -- Project information -----------------------------------------------------
changes: dict[str, dict] = keepachangelog.to_dict("../CHANGELOG.md")
latest_version: str = [
    v for v in changes.keys() if v not in ("Unreleased", "version_tag")
][0]

author: str = __about__.__author__
copyright: str = __about__.__copyright__
description: str = __about__.__summary__
project: str = __about__.__title__
version: str = __about__.__version__
release: str = latest_version

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions: list[str] = [
    # Sphinx included
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinx.ext.imgmath",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    # 3rd party
    "myst_parser",
    "sphinx_copybutton",
    "sphinxext.opengraph",
]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix: dict[str, str] = {".md": "markdown", ".rst": "restructuredtext"}
autosectionlabel_prefix_document: bool = True
# The master toctree document.
master_doc: str = "index"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns: list[str] = [
    "_build",
    ".venv",
    "Thumbs.db",
    ".DS_Store",
    "_output",
    "ext_libs",
    "tests",
    "demo",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# -- Theme

html_favicon = str(__about__.__icon_path__)
html_logo = str(__about__.__icon_path__)
html_theme = "furo"

# -- EXTENSIONS --------------------------------------------------------

# Sphinx API doc
autodoc_mock_imports: list[str] = [
    "qgis.core",
    "qgis.gui",
    "qgis.PyQt",
    "qgis.PyQt.QtCore",
    "qgis.PyQt.QtGui",
    "qgis.PyQt.QtNetwork",
    "qgis.PyQt.QtWidgets",
    "qgis.utils",
]

# Configuration for intersphinx (refer to others docs).
intersphinx_mapping: dict[str, tuple[str, None]] = {
    "PyQt5": ("https://www.riverbankcomputing.com/static/Docs/PyQt5", None),
    "PyQt6": ("https://www.riverbankcomputing.com/static/Docs/PyQt6", None),
    "python": ("https://docs.python.org/3/", None),
    "qgis": ("https://qgis.org/pyqgis/master/", None),
}

# MyST Parser
myst_enable_extensions: list[str] = [
    "colon_fence",
    "deflist",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
]

myst_substitutions: dict[str, str] = {
    "author": author,
    "date_update": datetime.now().strftime("%d %B %Y"),
    "description": __about__.__summary__,
    "qgis_version_max": __about__.__plugin_md__.get("general").get(
        "qgismaximumversion"
    ),
    "qgis_version_min": __about__.__plugin_md__.get("general").get(
        "qgisminimumversion"
    ),
    "repo_url": __about__.__uri__,
    "title": project,
    "version": version,
    "release_version": release,
}

myst_url_schemes: tuple[str, str, str] = ("http", "https", "mailto")

# OpenGraph
ogp_image: str = (
    f"{__about__.__uri_homepage__}_images/french_locator_sample_basque_qgis_details.png"
)
ogp_site_name: str = "French Locator Filter : géocodeur Français pour QGIS"
ogp_site_url: str = __about__.__uri_homepage__
ogp_custom_meta_tags: list[str] = [
    "<meta name='twitter:card' content='summary_large_image'>",
    f'<meta property="twitter:description" content="{description}" />',
    f'<meta property="twitter:image" content="{ogp_image}" />',
    '<meta property="twitter:site" content="@oslandia" />',
    f'<meta property="twitter:title" content="{project}" />',
]


# -- Functions ------------------------------------------------------------------
def generate_qdt_snippet(_) -> None:
    """Generate QDT snippet for profiles.json files."""
    logger.info("=== START GENERATING QDT SNIPPET ===")

    output_path: Path = Path("./docs/_static/autogenerated/qdt_snippet.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    qdt_snippet: dict[str, Union[str, bool, int]] = {
        "name": "French Locator Filter",
        "folder_name": "french_locator_filter",
        "official_repository": True,
        "plugin_id": 1846,
        "version": f"{latest_version}",
    }

    with output_path.open("w", encoding="UTF8") as wf:
        wf.write(json.dumps(qdt_snippet, indent=4, sort_keys=True))


# run api doc
def run_apidoc(_) -> None:
    """Run Sphinx apidoc to generate documentation from docstrings."""
    from sphinx.ext.apidoc import main

    logger.info("=== START SPHINX API AUTODOC ===")

    cur_dir: Path = Path(__file__).parent.resolve()
    output_path = str(cur_dir.joinpath("_apidoc").resolve())
    modules = str(cur_dir.joinpath("../french_locator_filter/").resolve())
    exclusions: list[str] = ["../.venv", "../tests"]
    main(["-e", "-f", "-M", "-o", output_path, modules] + exclusions)


# launch setup
def setup(app) -> None:
    """Setup Sphinx hooks."""
    app.connect("builder-inited", run_apidoc)
    app.connect("builder-inited", generate_qdt_snippet)
